import type { Metadata } from "next";
import "./globals.css";
// import { Nunito } from "next/font/google";
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import { ThemeProvider } from '@/components/ThemeProvider';


const nunito = Inter({
      subsets: ['latin'],
      weight: ['400', '700'], // Specify desired weights (e.g., regular and bold)
      display: 'swap', // Optimizes font loading behavior
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nunito.className} antialiased`}>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
