import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import Header from "@/components/Header";

const nunito = Nunito({
      subsets: ['latin'],
      weight: ['400', '700'], // Specify desired weights (e.g., regular and bold)
      display: 'swap', // Optimizes font loading behavior
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
